// File generated by Antigravity using google-services.json details.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF5IaQVjzivkSNSIT_SqsUAu7FTFn6ti8',
    appId: '1:913763493698:web:d96627cd15c7419f064adb',
    messagingSenderId: '913763493698',
    projectId: 'stock-archery-99',
    authDomain: 'stock-archery-99.firebaseapp.com',
    storageBucket: 'stock-archery-99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5IaQVjzivkSNSIT_SqsUAu7FTFn6ti8',
    appId: '1:913763493698:android:d96627cd15c7419f064adb',
    messagingSenderId: '913763493698',
    projectId: 'stock-archery-99',
    storageBucket: 'stock-archery-99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5IaQVjzivkSNSIT_SqsUAu7FTFn6ti8',
    appId: '1:913763493698:ios:d96627cd15c7419f064adb',
    messagingSenderId: '913763493698',
    projectId: 'stock-archery-99',
    storageBucket: 'stock-archery-99.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
